<a href="https://colab.research.google.com/github/netajik/mathematics-for-ml/blob/master/vector_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy is used for all types of array operations
import numpy as np

#vectors
v = np.array([1,-1,2])
w = np.array([2,5,2])

print("vector addition")
print(v+w)

print("substraction")
print(v-w)

#Scalar multiplication:
print(3*v)

print(np.linalg.norm(v))

print("dot product")
print(np.dot(v,w))


vector addition
[3 4 4]
substraction
[-1 -6  0]
[ 3 -3  6]
2.449489742783178
dot product
1
