<a href="https://colab.research.google.com/github/netajik/mathematics-for-ml/blob/master/vector_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy is used for all types of array operations
import numpy as np

#vectors
v = np.array([1,-1,2])
w = np.array([2,5,2])

print("vector addition")
print(v+w)

print("substraction")
print(v-w)

#Scalar multiplication:
print(3*v)

print(np.linalg.norm(v)) #length of vector

print("dot product")
print(np.dot(v,w))


vector addition
[3 4 4]
substraction
[-1 -6  0]
[ 3 -3  6]
2.449489742783178
dot product
1


In [18]:
#Matrix operations
import numpy as np
P = np.array([[1,7],[2,1],[3,2]])
print(P)
Q=np.array([[1,2],[1,-1],[1,0]])
print(Q)
C1=np.subtract(P,Q)
print(C1)

# np.dot(P,Q)  shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

R = np.array([[1,3,1],[1,0,1]])
C2 = np.dot(P,R)
print(C2)

det = np.linalg.det(C2)
print(det)

# S2 = np.linalg.inv(C2) Singular matrix, det of C2 is 0
# print(S2)

M = np.array([[1,-1],[2,3]])
print(M)
print(np.linalg.inv(M))


[[1 7]
 [2 1]
 [3 2]]
[[ 1  2]
 [ 1 -1]
 [ 1  0]]
[[0 5]
 [1 2]
 [2 2]]
[[8 3 8]
 [3 6 3]
 [5 9 5]]
0.0
[[ 1 -1]
 [ 2  3]]
[[ 0.6  0.2]
 [-0.4  0.2]]
